[project]
name = "iot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "coloredlogs>=15.0.1",
    "dotenv>=0.9.9",
    "paho-mqtt>=2.1.0",
]
